ALTER TABLE global_settings
  ADD COLUMN IF NOT EXISTS fajr_start_offset   INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fajr_iqamah_offset  INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS dhuhr_start_offset  INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS dhuhr_iqamah_offset INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS asr_start_offset    INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS asr_iqamah_offset   INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS isha_start_offset   INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS isha_iqamah_offset  INTEGER NOT NULL DEFAULT 0;
