-- ⚠️ DEPRECATED - DO NOT USE THIS MIGRATION ⚠️
--
-- This migration is no longer needed and should NOT be run.
--
-- REASON:
-- After implementing this migration, we realized Jumu'ah start time should
-- ALWAYS use the Dhuhr start time (not stored separately in the database).
--
-- The application now:
-- - Uses Dhuhr start time for Jumu'ah start (calculated at runtime)
-- - Only stores Jumu'ah iqamah in the database (jumuah_iqamah column)
--
-- If you already ran this migration and have a jumuah_start column,
-- please run: supabase-migration-jumuah-cleanup.sql to clean it up.
--
-- ============================================================
-- ORIGINAL MIGRATION (DO NOT USE)
-- ============================================================
-- Add the jumuah_start column (allow NULL for existing data)
-- ALTER TABLE excel_schedule
-- ADD COLUMN IF NOT EXISTS jumuah_start VARCHAR(20);
